salesforce/DeviceManager/force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>Device</label>
    <nameField>
        <label>Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/DeviceManager/force-app/main/default/objects/Device__c/fields/ExternalDeviceManagerAppId__c.field-meta.xml
<CustomField>
    <fullName>ExternalDeviceManagerAppId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ExternalDeviceManagerAppId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce/DeviceManager/force-app/main/default/objects/Device__c/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <label>Manufacturer</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

salesforce/DeviceManager/force-app/main/default/classes/DeviceDTO.cls
public class DeviceDTO {

    public String id;
    public String sfId;
    public String manufacturer;
    public String model;
    public Decimal price;
    
    public DeviceDTO(Device__c device) {
        this.id = device.ExternalDeviceManagerAppId__c;
        this.sfId = device.Id;
        this.manufacturer = device.Manufacturer__c;
        this.model = device.Name;
        this.price = device.Price__c;
    }
}