salesforce/DeviceManager/force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>Device</label>
    <nameField>
        <label>Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/DeviceManager/force-app/main/default/objects/Device__c/fields/ExternalDeviceManagerAppId__c.field-meta.xml
<CustomField>
    <fullName>ExternalDeviceManagerAppId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ExternalDeviceManagerAppId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce/DeviceManager/force-app/main/default/objects/Device__c/fields/LastlyModifiedByDMJavaApp__c.field-meta.xml
<CustomField>
    <fullName>LastlyModifiedByDMJavaApp__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lastly Modified By DM Java App</label>
    <type>Checkbox</type>
</CustomField>

salesforce/DeviceManager/force-app/main/default/objects/Device__c/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <label>Manufacturer</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

salesforce/DeviceManager/force-app/main/default/classes/DeviceSyncService.cls
public with sharing class DeviceSyncService {

    public static Boolean isItDmJavaAppIntegrationContext = false;

    public static void checkIfItIsDmJavaAppIntegrationContext(List<Device__c> newDevices){
        isItDmJavaAppIntegrationContext = newDevices[0].LastlyModifiedByDMJavaApp__c == true;
        if(isItDmJavaAppIntegrationContext){
            for(Device__c device: newDevices){
                device.LastlyModifiedByDMJavaApp__c = false;
            }
        }
    }
    
    public static List<DeviceDTO> convertDevicesToDTOs(List<Device__c> devices){
        List<DeviceDTO> dtos = new List<DeviceDTO>();
        for(Device__c device: devices){
            dtos.add(new DeviceDTO(device));
        }
        return dtos;
    }

    public static void updateExternalDMAppId(List<DeviceDTO> resDeviceDtos, Map<Id, Device__c> devicesMap){
        List<Device__c> devicesToUpdate = new List<Device__c>();
        for(DeviceDTO deviceDto: resDeviceDtos){
            Device__c device = devicesMap.get(deviceDto.sfId);
            if(device.ExternalDeviceManagerAppId__c != deviceDto.id){
                devicesToUpdate.add(
                    new Device__c(
                        Id = deviceDto.sfId,
                        ExternalDeviceManagerAppId__c = deviceDto.id
                    )
                );
            }
        }
        update devicesToUpdate;
    }

    public static List<Device__c> filterDevicesToSync(List<Device__c> newDevices, Map<Id, Device__c> oldDevicesMap){
        if(oldDevicesMap == null || oldDevicesMap.isEmpty()){
            return newDevices;
        }
        
        List<Device__c> devicesToSync = new List<Device__c>();
        for(Device__c newDevice: newDevices){
            Device__c oldDevice = oldDevicesMap.get(newDevice.Id);
            if(newDevice.Name != oldDevice.Name
                || newDevice.Manufacturer__c != oldDevice.Manufacturer__c
                || newDevice.Price__c != oldDevice.Price__c)
            {
                devicesToSync.add(newDevice);
            }
        }

        return devicesToSync;
    }

    public static void syncDevicesToExternalDMApp(List<Device__c> devicesToSync){
        if(devicesToSync != null && !devicesToSync.isEmpty()){
            DeviceSyncQueueable dsq = new DeviceSyncQueueable(
                new Map<Id, Device__c>(devicesToSync).keySet()
            );

            System.enqueueJob(dsq);
        }
    }



}