salesforce/DeviceManager/force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>Device</label>
    <nameField>
        <label>Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/DeviceManager/force-app/main/default/objects/Device__c/fields/ExternalDeviceManagerAppId__c.field-meta.xml
<CustomField>
    <fullName>ExternalDeviceManagerAppId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ExternalDeviceManagerAppId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce/DeviceManager/force-app/main/default/objects/Device__c/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <label>Manufacturer</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

salesforce/DeviceManager/force-app/main/default/classes/DeviceSyncQueueable.cls
public with sharing class DeviceSyncQueueable implements Queueable, Database.AllowsCallouts {

    private Set<Id> deviceIds;

    public DeviceSyncQueueable(Set<Id> deviceIds){
        this.deviceIds = deviceIds;
    }

    public void execute(QueueableContext context) {
        List<Device__c> devicesToSync = [
            SELECT Name, ExternalDeviceManagerAppId__c, Manufacturer__c, Price__c
            FROM Device__c
            WHERE Id IN :deviceIds
        ];

        String requestBody = JSON.serialize(
            DeviceSyncService.convertDevicesToDTOs(devicesToSync)
        );

        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:DM_Named_Credential/api/device/saveDevices');
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        req.setBody(requestBody);

        HTTPResponse res = new Http().send(req);
        String body = res.getBody();

        DeviceSyncService.updateExternalDMAppId( 
            (List<DeviceDTO>) JSON.deserialize(body, List<DeviceDTO>.class),
            new Map<Id, Device__c>(devicesToSync)
        );
    }

}